spring:
  application:
    name: provider
server:
  port: 8001
provider:
  name: provider1
eureka:
  client:
    service-url:
      defaultZone: http://node1:8081/eureka/,http://node2:8082/eureka/,http://node3:8082/eureka/
